const dataConfig = {
  simpleMenu: false,
  menu: {
    Works: {
      "Slide Carousel": "index.html",
      "Roll Carousel": "works-carousel-roll.html",
      "Fullscreen Slider": {
        "Parallax Movement": "works-slider-parallax.html",
        "Fade Sliding": "works-slider-fade.html",
        "Diagonally Sliced": "works-slider-sliced.html",
        "Pixel Storm": "works-slider-pixels.html",
      },
      "Flat Carousel": "works-carousel-flat.html",
    },
    Galleries: {
      "WebGL Carousel": "albums-gl-carousel.html",
      "Flat Carousel": "albums-carousel.html",
      Slider: {
        "Parallax Movement": "albums-slider-parallax.html",
        "Fade Sliding": "albums-slider-fade.html",
        "Diagonally Sliced": "albums-slider-sliced.html",
        "Pixel Storm": "albums-slider-pixels.html",
      },
      "Adjusted Grid": {
        "Adjusted: 2 Columns": "albums-adjusted-2col.html",
        "Adjusted: 3 Columns": "albums-adjusted-3col.html",
        "Adjusted: 4 Columns": "albums-adjusted-4col.html",
      },
      "Strong Grid": {
        "Grid: 2 Columns": "albums-grid-2col.html",
        "Grid: 3 Columns": "albums-grid-3col.html",
        "Grid: 4 Columns": "albums-grid-4col.html",
      },
      "Masonry Grid": {
        "Masonry: 2 Columns": "albums-masonry-2col.html",
        "Masonry: 3 Columns": "albums-masonry-3col.html",
        "Masonry: 4 Columns": "albums-masonry-4col.html",
      },
      Justified: "albums-justified.html",
      "Bricks 1x2": "albums-bricks-1x2.html",
      "Bricks 2x3": "albums-bricks-2x3.html",
    },
  },
  socials: {
    facebook: {
      url: "#",
      label: "Fb.",
    },
    twitter: {
      url: "#",
      label: "Tw.",
    },
    instagram: {
      url: "#",
      label: "In.",
    },
    youtube: {
      url: "#",
      label: "Yt.",
    },
    telegram: {
      url: "#",
      label: "tg.",
    },
  },
  copyright: "Copyright &copy; 2022. All Rights Reserved.",
  pages: {
    index: {
      pageTitle: "Anita | Creative Photography",
      favIconPath: "img/favicon.png",
      logoPath: "img/logo.png",
      listingType: "glCarousel",
      pageBackgroundSrc: "img/albums/covers_1920/album10_1920.jpg",
      items: [
        {
          isVideo: true,
          src: "video/albums/album01.mp4",
          size: "1280x720",
          subtitleTop: "Portraits",
          number: "01.",
          title: "Green Turban",
          subtitleBot: "Explore",
          href: "albums-gl-carousel.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album02_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Love Story",
          number: "02.",
          title: "Golden Feelings",
          subtitleBot: "Explore",
          href: "albums-masonry-2col.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album03_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Children",
          number: "03.",
          title: "Little Lady",
          subtitleBot: "Explore",
          href: "albums-slider-parallax.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album04_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Wedding",
          number: "04.",
          title: "Sweet Harmony",
          subtitleBot: "Explore",
          href: "albums-adjusted-3col.html",
        },
        {
          isVideo: true,
          src: "video/albums/album05.mp4",
          size: "1280x720",
          subtitleTop: "Portraits",
          number: "05.",
          title: "Holiday Makeup",
          subtitleBot: "Explore",
          href: "albums-slider-sliced.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album06_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Wedding",
          number: "06.",
          title: "The Big Day",
          subtitleBot: "Explore",
          href: "albums-bricks-1x2.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album07_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Love Story",
          number: "07.",
          title: "When You Love",
          subtitleBot: "Explore",
          href: "albums-bricks-2x3.html",
        },
        {
          isVideo: true,
          src: "video/albums/album08.mp4",
          size: "1280x720",
          subtitleTop: "Children",
          number: "08.",
          title: "Walking by Ocean",
          subtitleBot: "Explore",
          href: "albums-masonry-4col.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album09_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Portraits",
          number: "09.",
          title: "Beauty of the Wild",
          subtitleBot: "Explore",
          href: "albums-slider-fade.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album10_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Children",
          number: "10.",
          title: "Kids Happiness",
          subtitleBot: "Explore",
          href: "albums-adjusted-4col.html",
        },
        {
          isVideo: true,
          src: "video/albums/album11.mp4",
          size: "1280x720",
          subtitleTop: "Love Story",
          number: "11.",
          title: "Dia de Los Muertos",
          subtitleBot: "Explore",
          href: "albums-grid-3col.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album12_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Children",
          number: "12.",
          title: "Share Your Smile",
          subtitleBot: "Explore",
          href: "albums-justified.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album13_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Wedding",
          number: "13.",
          title: "From Now and Ever",
          subtitleBot: "Explore",
          href: "albums-adjusted-2col.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album14_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Children",
          number: "14.",
          title: "Autumn Gladness",
          subtitleBot: "Explore",
          href: "albums-slider-pixels.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album15_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Wedding",
          number: "15.",
          title: "Wedding Day",
          subtitleBot: "Explore",
          href: "albums-grid-4col.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album16_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Portraits",
          number: "16.",
          title: "Smiling Beauty",
          subtitleBot: "Explore",
          href: "albums-masonry-3col.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album17_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Love Story",
          number: "17.",
          title: "Underwater Love",
          subtitleBot: "Explore",
          href: "albums-grid-2col.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album18_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Portraits",
          number: "18.",
          title: "Bright Life Colors",
          subtitleBot: "Explore",
          href: "albums-carousel.html",
        },
      ],
    },
    "albums-gl-carousel": {
      pageTitle: "Anita | Creative Photography",
      favIconPath: "img/favicon.png",
      logoPath: "img/logo.png",
      listingType: "glCarousel",
      pageBackgroundSrc: "img/albums/covers_1920/album10_1920.jpg",
      albumTitle: {
        back: "Back to Listing",
        backPath: "index.html",
        title: "Green Turban",
        subtitle1: "Portraits",
        subtitle2: "10 Photos",
      },
      navigation: {
        subtitleLeft: "Prev Album",
        titleLeft: "Bright Life Colors",
        hrefLeft: "albums-carousel.html",
        srcLeft: "img/albums/covers_512/album18.jpg",
        subtitleRight: "Next Album",
        titleRight: "Golden Feelings",
        hrefRight: "albums-masonry-2col.html",
        srcRight: "img/albums/covers_512/album02.jpg",
      },
      items: [
        {
          src: "img/albums/album01/01.jpg",
          size: "1440x1080",
        },
        {
          src: "img/albums/album01/02.jpg",
          size: "800x1080",
        },
        {
          src: "img/albums/album01/03.jpg",
          size: "1440x1080",
        },

        {
          src: "img/albums/album01/04.jpg",
          size: "800x1080",
        },
        {
          src: "img/albums/album01/05.jpg",
          size: "1440x1080",
        },
        {
          src: "img/albums/album01/06.jpg",
          size: "800x1080",
        },
        {
          src: "img/albums/album01/07.jpg",
          size: "1440x1080",
        },
        {
          src: "img/albums/album01/08.jpg",
          size: "800x1080",
        },
        {
          src: "img/albums/album01/09.jpg",
          size: "1440x1080",
        },
        {
          src: "img/albums/album01/10.jpg",
          size: "800x1080",
        },
      ],
    },
    "albums-carousel": {
      pageTitle: "Anita | Bright Life Colors",
      favIconPath: "img/favicon.png",
      logoPath: "img/logo.png",
      listingType: "carousel",
      pageBackgroundSrc: "img/albums/covers_1920/album10_1920.jpg",
      albumTitle: {
        back: "Back to Listing",
        backPath: "index.html",
        title: " Bright Life Colors",
        subtitle1: "Portraits",
        subtitle2: "08 Photos",
      },
      navigation: {
        subtitleLeft: "Prev Album",
        titleLeft: "Underwater Love",
        hrefLeft: "albums-grid-2col.html",
        srcLeft: "img/albums/covers_512/album17.jpg",
        subtitleRight: "Next Album",
        titleRight: "Green Turban",
        hrefRight: "albums-gl-carousel.html",
        srcRight: "img/albums/covers_512/album01.jpg",
      },
      items: [
        {
          src: "img/albums/album18/01.jpg",
          alt: "Photo 01",
          width: "800",
          height: "1080",
        },
        {
          src: "img/albums/album18/02.jpg",
          alt: "Photo 02",
          width: "800",
          height: "1080",
        },
        {
          src: "img/albums/album18/03.jpg",
          alt: "Photo 03",
          width: "800",
          height: "1080",
        },
        {
          src: "img/albums/album18/04.jpg",
          alt: "Photo 04",
          width: "800",
          height: "1080",
        },
        {
          src: "img/albums/album18/05.jpg",
          alt: "Photo 05",
          width: "800",
          height: "1080",
        },
        {
          src: "img/albums/album18/06.jpg",
          alt: "Photo 06",
          width: "800",
          height: "1080",
        },
        {
          src: "img/albums/album18/07.jpg",
          alt: "Photo 07",
          width: "800",
          height: "1080",
        },
        {
          src: "img/albums/album18/08.jpg",
          alt: "Photo 08",
          width: "800",
          height: "1080",
        },
      ],
    },
    "albums-masonry-2col": {
      pageTitle: "Anita | Golden Feelings",
      favIconPath: "img/favicon.png",
      logoPath: "img/logo.png",
      listingType: "masonry",
      pageBackgroundSrc: "img/albums/covers_1920/album10_1920.jpg",
      albumTitle: {
        back: "Back to Listing",
        backPath: "index.html",
        title: "Golden Feelings",
        subtitle1: "Love Story",
        subtitle2: "06 Photos",
        description:
          "Autumn is a perfect time for a romantic love story photo session. When trees are covered with gold and fallen leaves are all around, the weather is cool but such hot feelings can warm all around.",
      },
      nextAlbum: {
        subtitle: "Next Album",
        title: "Little Lady",
        src: "img/albums/covers_512/album03.jpg",
        href: "albums-slider-parallax.html",
      },
      col: 2,
      items: [
        {
          src: "img/albums/album02/02.jpg",
          alt: "Photo 02",
          width: "1240",
          height: "960",
          size: "1240x960",
          href: "video/albums/album11.mp4",
          isVideo: true,
        },
        {
          src: "img/albums/album02/03.jpg",
          alt: "Photo 03",
          width: "930",
          height: "1080",
          size: "930x1080",
          href: "img/albums/album02/03.jpg",
        },
        {
          src: "img/albums/album02/04.jpg",
          alt: "Photo 04",
          width: "1240",
          height: "960",
          size: "1240x960",
          href: "img/albums/album02/04.jpg",
        },
        {
          src: "img/albums/album02/05.jpg",
          alt: "Photo 05",
          width: "930",
          height: "1080",
          size: "930x1080",
          href: "img/albums/album02/05.jpg",
        },
        {
          src: "img/albums/album02/06.jpg",
          alt: "Photo 06",
          width: "1080",
          height: "1080",
          size: "1080x1080",
          href: "img/albums/album02/06.jpg",
        },
      ],
    },
    "albums-masonry-3col": {
      pageTitle: "Anita | Smiling Beauty",
      favIconPath: "img/favicon.png",
      logoPath: "img/logo.png",
      listingType: "masonry",
      pageBackgroundSrc: "img/albums/covers_1920/album10_1920.jpg",
      albumTitle: {
        back: "Back to Listing",
        backPath: "index.html",
        title: "Smiling Beauty",
        subtitle1: "Portraits",
        subtitle2: "12 Photos",
        description:
          "What best decorates any beautiful girl? Of course, a sincere and charming smile. I’m glad to share with you the photography session with the gorgeous and charming girl. Be careful: her smile kills. :)",
      },
      nextAlbum: {
        subtitle: "Next Album",
        title: "Underwater Love",
        src: "img/albums/covers_512/album07.jpg",
        href: "albums-grid-2col.html",
      },
      col: 3,
      items: [
        {
          src: "img/albums/album16/01.jpg",
          alt: "Photo 01",
          width: "900",
          height: "1080",
          size: "900x1080",
          href: "video/albums/album11.mp4",
          isVideo: true,
        },
        {
          src: "img/albums/album16/02.jpg",
          alt: "Photo 02",
          width: "1200",
          height: "960",
          size: "1200x960",
          href: "img/albums/album16/02.jpg",
        },
        {
          src: "img/albums/album16/03.jpg",
          alt: "Photo 03",
          width: "900",
          height: "1080",
          size: "900x1080",
          href: "img/albums/album16/03.jpg",
        },
        {
          src: "img/albums/album16/04.jpg",
          alt: "Photo 04",
          width: "900",
          height: "1080",
          size: "900x1080",
          href: "img/albums/album16/04.jpg",
        },
        {
          src: "img/albums/album16/05.jpg",
          alt: "Photo 05",
          width: "900",
          height: "1080",
          size: "900x1080",
          href: "img/albums/album16/05.jpg",
        },
        {
          src: "img/albums/album16/06.jpg",
          alt: "Photo 06",
          width: "900",
          height: "1080",
          size: "900x1080",
          href: "img/albums/album16/06.jpg",
        },

        {
          src: "img/albums/album16/07.jpg",
          alt: "Photo 07",
          width: "900",
          height: "1080",
          size: "900x1080",
          href: "img/albums/album16/07.jpg",
        },
        {
          src: "img/albums/album16/08.jpg",
          alt: "Photo 08",
          width: "900",
          height: "1080",
          size: "900x1080",
          href: "img/albums/album16/08.jpg",
        },
        {
          src: "img/albums/album16/09.jpg",
          alt: "Photo 09",
          width: "1200",
          height: "960",
          size: "1200x960",
          href: "img/albums/album16/09.jpg",
        },
        {
          src: "img/albums/album16/10.jpg",
          alt: "Photo 10",
          width: "1200",
          height: "960",
          size: "1200x960",
          href: "img/albums/album16/10.jpg",
        },
        {
          src: "img/albums/album16/11.jpg",
          alt: "Photo 11",
          width: "1200",
          height: "900",
          size: "1200x900",
          href: "img/albums/album16/11.jpg",
        },
      ],
    },
    "albums-masonry-4col": {
      pageTitle: "Anita | Walking by Ocean",
      favIconPath: "img/favicon.png",
      logoPath: "img/logo.png",
      listingType: "masonry",
      pageBackgroundSrc: "img/albums/covers_1920/album10_1920.jpg",
      albumTitle: {
        back: "Back to Listing",
        backPath: "index.html",
        title: "Walking by Ocean",
        subtitle1: "Children",
        subtitle2: "12 Photos",
        description:
          "Kids are our future, our sunshine flowers of life. This kid only starts with the first steps in life and gets to know the world around him. Let me show you this gorgeous photo set with a mother and her child.",
      },
      nextAlbum: {
        subtitle: "Next Album",
        title: "Beauty of the Wild",
        src: "img/albums/covers_512/album09.jpg",
        href: "albums-slider-fade.html",
      },
      col: 4,
      items: [
        {
          src: "img/albums/album08/01.jpg",
          alt: "Photo 01",
          width: "1160",
          height: "920",
          size: "1160x920",
          href: "video/albums/album11.mp4",
          isVideo: true,
        },
        {
          src: "img/albums/album08/02.jpg",
          alt: "Photo 02",
          width: "895",
          height: "1080",
          size: "895x1080",
          href: "img/albums/album08/02.jpg",
        },
        {
          src: "img/albums/album08/03.jpg",
          alt: "Photo 03",
          width: "1160",
          height: "920",
          size: "1160x920",
          href: "img/albums/album08/03.jpg",
        },
        {
          src: "img/albums/album08/04.jpg",
          alt: "Photo 04",
          width: "895",
          height: "1080",
          size: "895x1080",
          href: "img/albums/album08/04.jpg",
        },

        {
          src: "img/albums/album08/05.jpg",
          alt: "Photo 05",
          width: "783",
          height: "1080",
          size: "783x1080",
          href: "img/albums/album08/05.jpg",
        },
        {
          src: "img/albums/album08/06.jpg",
          alt: "Photo 06",
          width: "1160",
          height: "656",
          size: "1160x656",
          href: "img/albums/album08/06.jpg",
        },
        {
          src: "img/albums/album08/07.jpg",
          alt: "Photo 07",
          width: "1160",
          height: "656",
          size: "1160x656",
          href: "img/albums/album08/07.jpg",
        },
        {
          src: "img/albums/album08/08.jpg",
          alt: "Photo 08",
          width: "1160",
          height: "656",
          size: "1160x656",
          href: "img/albums/album08/08.jpg",
        },
        {
          src: "img/albums/album08/09.jpg",
          alt: "Photo 09",
          width: "783",
          height: "1080",
          size: "783x1080",
          href: "img/albums/album08/09.jpg",
        },
        {
          src: "img/albums/album08/10.jpg",
          alt: "Photo 10",
          width: "895",
          height: "1080",
          size: "895x1080",
          href: "img/albums/album08/10.jpg",
        },
        {
          src: "img/albums/album08/11.jpg",
          alt: "Photo 11",
          width: "895",
          height: "1080",
          size: "895x1080",
          href: "img/albums/album08/11.jpg",
        },
        {
          src: "img/albums/album08/12.jpg",
          alt: "Photo 12",
          width: "895",
          height: "1080",
          size: "895x1080",
          href: "img/albums/album08/12.jpg",
        },
      ],
    },
    "albums-adjusted-2col": {
      pageTitle: "Anita | From Now and Ever",
      favIconPath: "img/favicon.png",
      logoPath: "img/logo.png",
      listingType: "adjusted",
      pageBackgroundSrc: "img/albums/covers_1920/album10_1920.jpg",
      albumTitle: {
        back: "Back to Listing",
        backPath: "index.html",
        title: "From Now and Ever",
        subtitle1: "Wedding",
        subtitle2: "08 Photos",
        description:
          "In this wedding photo session, the beauty of mother nature is the best background for such an amazing couple. Take a look at how harmonic looks in the white wedding dress on these green trees’ background.",
      },
      nextAlbum: {
        subtitle: "Next Album",
        title: "Autumn Gladness",
        src: "img/albums/covers_512/album14.jpg",
        href: "albums-slider-pixels.html",
      },
      col: 2,
      items: [
        {
          src: "img/albums/album13/01.jpg",
          alt: "Photo 01",
          width: "1046",
          height: "1080",
          size: "1046x1080",
          href: "video/albums/album11.mp4",
          isVideo: true,
        },
        {
          src: "img/albums/album13/02.jpg",
          alt: "Photo 02",
          width: "1240",
          height: "960",
          size: "1240x960",
          href: "img/albums/album13/02.jpg",
        },
        {
          src: "img/albums/album13/03.jpg",
          alt: "Photo 03",
          width: "1240",
          height: "960",
          size: "1240x960",
          href: "img/albums/album13/03.jpg",
        },
        {
          src: "img/albums/album13/04.jpg",
          alt: "Photo 04",
          width: "1046",
          height: "1080",
          size: "1046x1080",
          href: "img/albums/album13/04.jpg",
        },
        {
          src: "img/albums/album13/05.jpg",
          alt: "Photo 05",
          width: "1046",
          height: "1080",
          size: "1046x1080",
          href: "img/albums/album13/05.jpg",
        },
        {
          src: "img/albums/album13/06.jpg",
          alt: "Photo 06",
          width: "1240",
          height: "960",
          size: "1240x960",
          href: "img/albums/album13/06.jpg",
        },
        {
          src: "img/albums/album13/07.jpg",
          alt: "Photo 07",
          width: "1240",
          height: "960",
          size: "1240x960",
          href: "img/albums/album13/07.jpg",
        },
        {
          src: "img/albums/album13/08.jpg",
          alt: "Photo 08",
          width: "1046",
          height: "1080",
          size: "1046x1080",
          href: "img/albums/album13/08.jpg",
        },
      ],
    },
    "albums-adjusted-3col": {
      pageTitle: "Anita | Sweet Harmony",
      favIconPath: "img/favicon.png",
      logoPath: "img/logo.png",
      listingType: "adjusted",
      pageBackgroundSrc: "img/albums/covers_1920/album04_1920.jpg",
      albumTitle: {
        back: "Back to Listing",
        backPath: "index.html",
        title: "Sweet Harmony",
        subtitle1: "Wedding",
        subtitle2: "09 Photos",
        description:
          "In this photo session, I want to share with you the wedding photos of this beautiful couple. I’m very happy that they invite me to share this important moment in their life with me.",
      },
      nextAlbum: {
        subtitle: "Next Album",
        title: "Holiday Makeup",
        src: "img/albums/covers_512/album05.jpg",
        href: "albums-slider-sliced.html",
      },
      col: 3,
      items: [
        {
          src: "img/albums/album04/01.jpg",
          alt: "Photo 01",
          width: "1200",
          height: "960",
          size: "1200x960",
          href: "video/albums/album11.mp4",
          isVideo: true,
        },
        {
          src: "img/albums/album04/02.jpg",
          alt: "Photo 02",
          width: "900",
          height: "1080",
          size: "900x1080",
          href: "img/albums/album04/02.jpg",
        },
        {
          src: "img/albums/album04/03.jpg",
          alt: "Photo 03",
          width: "1200",
          height: "960",
          size: "1200x960",
          href: "img/albums/album04/03.jpg",
        },
        {
          src: "img/albums/album04/04.jpg",
          alt: "Photo 04",
          width: "900",
          height: "1080",
          size: "900x1080",
          href: "img/albums/album04/04.jpg",
        },
        {
          src: "img/albums/album04/05.jpg",
          alt: "Photo 05",
          width: "1200",
          height: "960",
          size: "1200x960",
          href: "img/albums/album04/05.jpg",
        },
        {
          src: "img/albums/album04/06.jpg",
          alt: "Photo 06",
          width: "900",
          height: "1080",
          size: "900x1080",
          href: "img/albums/album04/06.jpg",
        },
        {
          src: "img/albums/album04/07.jpg",
          alt: "Photo 07",
          width: "1200",
          height: "960",
          size: "1200x960",
          href: "img/albums/album04/07.jpg",
        },
        {
          src: "img/albums/album04/08.jpg",
          alt: "Photo 08",
          width: "900",
          height: "1080",
          size: "900x1080",
          href: "img/albums/album04/08.jpg",
        },
        {
          src: "img/albums/album04/09.jpg",
          alt: "Photo 09",
          width: "1200",
          height: "960",
          size: "1200x960",
          href: "img/albums/album04/09.jpg",
        },
      ],
    },
    "albums-adjusted-4col": {
      pageTitle: "Anita | Kids Happiness",
      favIconPath: "img/favicon.png",
      logoPath: "img/logo.png",
      listingType: "adjusted",
      albumTitle: {
        back: "Back to Listing",
        backPath: "index.html",
        title: "Kids Happiness",
        subtitle1: "Children",
        subtitle2: "12 Photos",
        description:
          "When kids are smiling, all the world around them smiling too. And when children are happy, we are happy with them. In this colorful photo session, children are glad to share their smiles with you.",
      },
      nextAlbum: {
        subtitle: "Next Album",
        title: "Da de Los Muertos",
        src: "img/albums/covers_512/album11.jpg",
        href: "albums-grid-3col.html",
      },
      col: 4,
      items: [
        {
          src: "img/albums/album10/01.jpg",
          alt: "Photo 01",
          width: "1160",
          height: "920",
          size: "1160x920",
          href: "img/albums/album10/01.jpg",
        },
        {
          src: "img/albums/album10/02.jpg",
          alt: "Photo 02",
          width: "895",
          height: "1080",
          size: "895x1080",
          href: "img/albums/album10/02.jpg",
        },
        {
          src: "img/albums/album10/03.jpg",
          alt: "Photo 03",
          width: "1160",
          height: "920",
          size: "1160x920",
          href: "img/albums/album10/03.jpg",
        },
        {
          src: "img/albums/album10/04.jpg",
          alt: "Photo 04",
          width: "895",
          height: "1080",
          size: "895x1080",
          href: "img/albums/album10/04.jpg",
        },
        {
          src: "img/albums/album10/05.jpg",
          alt: "Photo 05",
          width: "895",
          height: "1080",
          size: "895x1080",
          href: "img/albums/album10/05.jpg",
        },
        {
          src: "img/albums/album10/06.jpg",
          alt: "Photo 06",
          width: "1160",
          height: "920",
          size: "1160x920",
          href: "img/albums/album10/06.jpg",
        },
        {
          src: "img/albums/album10/07.jpg",
          alt: "Photo 07",
          width: "895",
          height: "1080",
          size: "895x1080",
          href: "img/albums/album10/07.jpg",
        },
        {
          src: "img/albums/album10/08.jpg",
          alt: "Photo 08",
          width: "1160",
          height: "920",
          size: "1160x920",
          href: "img/albums/album10/08.jpg",
        },
        {
          src: "img/albums/album10/09.jpg",
          alt: "Photo 09",
          width: "1160",
          height: "920",
          size: "1160x920",
          href: "img/albums/album10/09.jpg",
        },
        {
          src: "img/albums/album10/10.jpg",
          alt: "Photo 10",
          width: "895",
          height: "1080",
          size: "895x1080",
          href: "img/albums/album10/10.jpg",
        },
        {
          src: "img/albums/album10/11.jpg",
          alt: "Photo 11",
          width: "1160",
          height: "920",
          size: "1160x920",
          href: "img/albums/album10/11.jpg",
        },
        {
          src: "img/albums/album10/12.jpg",
          alt: "Photo 12",
          width: "895",
          height: "1080",
          size: "895x1080",
          href: "img/albums/album10/12.jpg",
        },
      ],
    },
    "albums-bricks-1x2": {
      pageTitle: "Anita | The Big Day",
      favIconPath: "img/favicon.png",
      logoPath: "img/logo.png",
      listingType: "bricks",
      pageBackgroundSrc: "img/albums/covers_1920/album04_1920.jpg",
      albumTitle: {
        back: "Back to Listing",
        backPath: "index.html",
        title: "The Big Day",
        subtitle1: "Wedding",
        subtitle2: "06 Photos",
        description:
          "This charming couple is celebrating their wedding. It was a real pleasure to capture that really Big Day in their lives in these romantic photos filled with love.",
      },
      nextAlbum: {
        subtitle: "Next Album",
        title: "When You Love",
        src: "img/albums/covers_512/album07.jpg",
        href: "albums-bricks-2x3.html",
      },
      col: "1x2",
      items: [
        {
          src: "img/albums/album06/01.jpg",
          alt: "Photo 01",
          width: "1240",
          height: "930",
          size: "1240x930",
          href: "img/albums/album06/01.jpg",
        },
        {
          src: "img/albums/album06/02.jpg",
          alt: "Photo 02",
          width: "1240",
          height: "930",
          size: "1240x930",
          href: "img/albums/album06/02.jpg",
        },
        {
          src: "img/albums/album06/03.jpg",
          alt: "Photo 03",
          width: "1440",
          height: "1080",
          size: "1440x1080",
          href: "img/albums/album06/03.jpg",
        },
        {
          src: "img/albums/album06/04.jpg",
          alt: "Photo 04",
          width: "1240",
          height: "930",
          size: "1240x930",
          href: "img/albums/album06/04.jpg",
        },
        {
          src: "img/albums/album06/05.jpg",
          alt: "Photo 05",
          width: "1240",
          height: "930",
          size: "1240x930",
          href: "img/albums/album06/05.jpg",
        },
        {
          src: "img/albums/album06/06.jpg",
          alt: "Photo 06",
          width: "1440",
          height: "1080",
          size: "1440x1080",
          href: "img/albums/album06/06.jpg",
        },
      ],
    },
    "albums-bricks-2x3": {
      pageTitle: "Anita | When You Love",
      favIconPath: "img/favicon.png",
      logoPath: "img/logo.png",
      listingType: "bricks",
      pageBackgroundSrc: "img/albums/covers_1920/album04_1920.jpg",
      albumTitle: {
        back: "Back to Listing",
        backPath: "index.html",
        title: "When You Love",
        subtitle1: "Love Story",
        subtitle2: "10 Photos",
        description:
          "When you love someone, there is nothing else that matters. Take a look at this beautiful couple, where love takes the first place in their lives. They look so happy and bright, and they really are!",
      },
      nextAlbum: {
        subtitle: "Next Album",
        title: "Walking by Ocean",
        src: "img/albums/covers_512/album08.jpg",
        href: "albums-masonry-4col.html",
      },
      col: "2x3",
      items: [
        {
          src: "img/albums/album07/01.jpg",
          alt: "Photo 01",
          width: "1200",
          height: "900",
          size: "1200x900",
          href: "img/albums/album07/01.jpg",
        },
        {
          src: "img/albums/album07/02.jpg",
          alt: "Photo 02",
          width: "1200",
          height: "900",
          size: "1200x900",
          href: "img/albums/album07/02.jpg",
        },
        {
          src: "img/albums/album07/03.jpg",
          alt: "Photo 03",
          width: "1200",
          height: "900",
          size: "1200x900",
          href: "img/albums/album07/03.jpg",
        },
        {
          src: "img/albums/album07/04.jpg",
          alt: "Photo 04",
          width: "1440",
          height: "1080",
          size: "1440x1080",
          href: "img/albums/album07/04.jpg",
        },
        {
          src: "img/albums/album07/05.jpg",
          alt: "Photo 05",
          width: "1440",
          height: "1080",
          size: "1440x1080",
          href: "img/albums/album07/05.jpg",
        },
        {
          src: "img/albums/album07/06.jpg",
          alt: "Photo 06",
          width: "1200",
          height: "900",
          size: "1200x900",
          href: "img/albums/album07/06.jpg",
        },
        {
          src: "img/albums/album07/07.jpg",
          alt: "Photo 07",
          width: "1200",
          height: "900",
          size: "1200x900",
          href: "img/albums/album07/07.jpg",
        },
        {
          src: "img/albums/album07/08.jpg",
          alt: "Photo 08",
          width: "1200",
          height: "900",
          size: "1200x900",
          href: "img/albums/album07/08.jpg",
        },
        {
          src: "img/albums/album07/09.jpg",
          alt: "Photo 09",
          width: "1440",
          height: "1080",
          size: "1440x1080",
          href: "img/albums/album07/09.jpg",
        },
        {
          src: "img/albums/album07/10.jpg",
          alt: "Photo 10",
          width: "1440",
          height: "1080",
          size: "1440x1080",
          href: "img/albums/album07/10.jpg",
        },
      ],
    },
    "albums-grid-2col": {
      pageTitle: "Anita | Underwater Love",
      favIconPath: "img/favicon.png",
      logoPath: "img/logo.png",
      listingType: "grid",
      pageBackgroundSrc: "img/albums/covers_1920/album04_1920.jpg",
      albumTitle: {
        back: "Back to Listing",
        backPath: "index.html",
        title: "Underwater Love",
        subtitle1: "Love Story",
        subtitle2: "08 Photos",
        description:
          "When you realize that your love is so great that it does not fit on earth, you move deeper to share your love not only on earth but even underwater. Take a look at how amazing is the result of such an experiment.",
      },
      nextAlbum: {
        subtitle: "Next Album",
        title: "Bright Life Colors",
        src: "img/albums/covers_512/album18.jpg",
        href: "albums-carousel.html",
      },
      col: 2,
      items: [
        {
          src: "img/albums/album17/01.jpg",
          alt: "Photo 01",
          width: "1240",
          height: "930",
          size: "1240x930",
          href: "img/albums/album17/01.jpg",
        },
        {
          src: "img/albums/album17/02.jpg",
          alt: "Photo 02",
          width: "1240",
          height: "930",
          size: "1240x930",
          href: "img/albums/album17/02.jpg",
        },
        {
          src: "img/albums/album17/03.jpg",
          alt: "Photo 03",
          width: "1240",
          height: "930",
          size: "1240x930",
          href: "img/albums/album17/03.jpg",
        },
        {
          src: "img/albums/album17/04.jpg",
          alt: "Photo 04",
          width: "1240",
          height: "930",
          size: "1240x930",
          href: "img/albums/album17/04.jpg",
        },
        {
          src: "img/albums/album17/05.jpg",
          alt: "Photo 05",
          width: "1240",
          height: "930",
          size: "1240x930",
          href: "img/albums/album17/05.jpg",
        },
        {
          src: "img/albums/album17/06.jpg",
          alt: "Photo 06",
          width: "1240",
          height: "930",
          size: "1240x930",
          href: "img/albums/album17/06.jpg",
        },
        {
          src: "img/albums/album17/07.jpg",
          alt: "Photo 07",
          width: "1240",
          height: "930",
          size: "1240x930",
          href: "img/albums/album17/07.jpg",
        },
        {
          src: "img/albums/album17/08.jpg",
          alt: "Photo 08",
          width: "1240",
          height: "930",
          size: "1240x930",
          href: "img/albums/album17/08.jpg",
        },
      ],
    },
    "albums-grid-3col": {
      pageTitle: "Anita | Da de Los Muertos",
      favIconPath: "img/favicon.png",
      logoPath: "img/logo.png",
      listingType: "grid",
      albumTitle: {
        back: "Back to Listing",
        backPath: "index.html",
        title: "Da de Los Muertos",
        subtitle1: "Love Story",
        subtitle2: "12 Photos",
        description:
          "Da de Los Muertos is a holiday that involves family and friends gathering to pay respects and remember friends and family members who have died. This couple in love is not an exception.",
      },
      nextAlbum: {
        subtitle: "Next Album",
        title: "Share Your Smile",
        src: "img/albums/covers_512/album12.jpg",
        href: "albums-justified.html",
      },
      col: 3,
      items: [
        {
          src: "img/albums/album11/01.jpg",
          alt: "Photo 01",
          width: "1200",
          height: "900",
          size: "1280x720",
          href: "video/albums/album11.mp4",
          isVideo: true,
        },
        {
          src: "img/albums/album11/02.jpg",
          alt: "Photo 02",
          width: "1200",
          height: "900",
          size: "1160x920",
          href: "img/albums/album11/02.jpg",
        },
        {
          src: "img/albums/album11/03.jpg",
          alt: "Photo 03",
          width: "1200",
          height: "900",
          size: "1160x920",
          href: "img/albums/album11/03.jpg",
        },
        {
          src: "img/albums/album11/04.jpg",
          alt: "Photo 04",
          width: "1200",
          height: "900",
          size: "1160x920",
          href: "img/albums/album11/04.jpg",
        },
        {
          src: "img/albums/album11/05.jpg",
          alt: "Photo 05",
          width: "1200",
          height: "900",
          size: "1160x920",
          href: "img/albums/album11/05.jpg",
        },
        {
          src: "img/albums/album11/06.jpg",
          alt: "Photo 06",
          width: "1200",
          height: "900",
          size: "1160x920",
          href: "img/albums/album11/06.jpg",
        },
        {
          src: "img/albums/album11/07.jpg",
          alt: "Photo 07",
          width: "1200",
          height: "900",
          size: "1160x920",
          href: "img/albums/album11/07.jpg",
        },
        {
          src: "img/albums/album11/08.jpg",
          alt: "Photo 08",
          width: "1200",
          height: "900",
          size: "1160x920",
          href: "img/albums/album11/08.jpg",
        },
        {
          src: "img/albums/album11/09.jpg",
          alt: "Photo 09",
          width: "1200",
          height: "900",
          size: "1160x920",
          href: "img/albums/album11/09.jpg",
        },
        {
          src: "img/albums/album11/10.jpg",
          alt: "Photo 10",
          width: "1200",
          height: "900",
          size: "1160x920",
          href: "img/albums/album11/10.jpg",
        },
        {
          src: "img/albums/album11/11.jpg",
          alt: "Photo 11",
          width: "1200",
          height: "900",
          size: "1160x920",
          href: "img/albums/album11/11.jpg",
        },
        {
          src: "img/albums/album11/12.jpg",
          alt: "Photo 12",
          width: "1200",
          height: "900",
          size: "1160x920",
          href: "img/albums/album11/12.jpg",
        },
      ],
    },
    "albums-grid-4col": {
      pageTitle: "Anita | Wedding Day",
      favIconPath: "img/favicon.png",
      logoPath: "img/logo.png",
      listingType: "grid",
      pageBackgroundSrc: "img/albums/covers_1920/album15_1920.jpg",
      albumTitle: {
        back: "Back to Listing",
        backPath: "index.html",
        title: "Wedding Day",
        subtitle1: "Wedding",
        subtitle2: "16 Photos",
        description:
          "Wedding day is one of the most important big days in our lives. We spend a lot of effort to make this magical day just one of the best days in our life, where everything is perfect and right in place.",
      },
      nextAlbum: {
        subtitle: "Next Album",
        title: "Smiling Beauty",
        src: "img/albums/covers_512/album16.jpg",
        href: "albums-masonry-3col.html",
      },
      col: 4,
      items: [
        {
          src: "img/albums/album15/01.jpg",
          alt: "Photo 01",
          width: "1160",
          height: "872",
          size: "1160x872",
          href: "img/albums/album15/01.jpg",
        },
        {
          src: "img/albums/album15/02.jpg",
          alt: "Photo 02",
          width: "1160",
          height: "872",
          size: "1160x872",
          href: "img/albums/album15/02.jpg",
        },
        {
          src: "img/albums/album15/03.jpg",
          alt: "Photo 03",
          width: "1160",
          height: "872",
          size: "1160x872",
          href: "img/albums/album15/03.jpg",
        },
        {
          src: "img/albums/album15/04.jpg",
          alt: "Photo 04",
          width: "1160",
          height: "872",
          size: "1160x872",
          href: "img/albums/album15/04.jpg",
        },
        {
          src: "img/albums/album15/05.jpg",
          alt: "Photo 05",
          width: "1160",
          height: "872",
          size: "1160x872",
          href: "img/albums/album15/05.jpg",
        },
        {
          src: "img/albums/album15/06.jpg",
          alt: "Photo 06",
          width: "1160",
          height: "872",
          size: "1160x872",
          href: "img/albums/album15/06.jpg",
        },
        {
          src: "img/albums/album15/07.jpg",
          alt: "Photo 07",
          width: "1160",
          height: "872",
          size: "1160x872",
          href: "img/albums/album15/07.jpg",
        },
        {
          src: "img/albums/album15/08.jpg",
          alt: "Photo 08",
          width: "1160",
          height: "872",
          size: "1160x872",
          href: "img/albums/album15/08.jpg",
        },
        {
          src: "img/albums/album15/09.jpg",
          alt: "Photo 09",
          width: "1160",
          height: "872",
          size: "1160x872",
          href: "img/albums/album15/09.jpg",
        },
        {
          src: "img/albums/album15/10.jpg",
          alt: "Photo 10",
          width: "1160",
          height: "872",
          size: "1160x872",
          href: "img/albums/album15/10.jpg",
        },
        {
          src: "img/albums/album15/11.jpg",
          alt: "Photo 11",
          width: "1160",
          height: "872",
          size: "1160x872",
          href: "img/albums/album15/11.jpg",
        },
        {
          src: "img/albums/album15/12.jpg",
          alt: "Photo 12",
          width: "1160",
          height: "872",
          size: "1160x872",
          href: "img/albums/album15/12.jpg",
        },
        {
          src: "img/albums/album15/13.jpg",
          alt: "Photo 13",
          width: "1160",
          height: "872",
          size: "1160x872",
          href: "img/albums/album15/13.jpg",
        },
        {
          src: "img/albums/album15/14.jpg",
          alt: "Photo 14",
          width: "1160",
          height: "872",
          size: "1160x872",
          href: "img/albums/album15/14.jpg",
        },
        {
          src: "img/albums/album15/15.jpg",
          alt: "Photo 15",
          width: "1160",
          height: "872",
          size: "1160x872",
          href: "img/albums/album15/15.jpg",
        },
        {
          src: "img/albums/album15/16.jpg",
          alt: "Photo 16",
          width: "1160",
          height: "872",
          size: "1160x872",
          href: "img/albums/album15/16.jpg",
        },
      ],
    },
    "albums-justified": {
      pageTitle: "Anita | Share Your Smile",
      favIconPath: "img/favicon.png",
      logoPath: "img/logo.png",
      listingType: "justified",
      pageBackgroundSrc: "img/albums/covers_1920/album12_1920.jpg",
      albumTitle: {
        back: "Back to Listing",
        backPath: "index.html",
        title: "Share Your Smile",
        subtitle1: "Children",
        subtitle2: "22 Photos",
        description:
          "When kids are smiling, all the world around them smiling too. And when children are happy, we are happy with them. In this colorful photo session, children are glad to share their smiles with you.",
      },
      nextAlbum: {
        subtitle: "Next Album",
        title: "From Now and Ever",
        src: "img/albums/covers_512/album13.jpg",
        href: "albums-adjusted-2col.html",
      },
      items: [
        {
          src: "img/albums/album12/01.jpg",
          alt: "Photo 01",
          width: "1620",
          height: "1080",
          size: "1620x1080",
          href: "img/albums/album12/01.jpg",
        },
        {
          src: "img/albums/album12/02.jpg",
          alt: "Photo 02",
          width: "585",
          height: "1080",
          size: "585x1080",
          href: "img/albums/album12/02.jpg",
        },
        {
          src: "img/albums/album12/03.jpg",
          alt: "Photo 03",
          width: "1620",
          height: "1080",
          size: "1620x1080",
          href: "img/albums/album12/03.jpg",
        },
        {
          src: "img/albums/album12/04.jpg",
          alt: "Photo 04",
          width: "810",
          height: "1080",
          size: "810x1080",
          href: "img/albums/album12/04.jpg",
        },
        {
          src: "img/albums/album12/05.jpg",
          alt: "Photo 05",
          width: "720",
          height: "1080",
          size: "720x1080",
          href: "img/albums/album12/05.jpg",
        },
        {
          src: "img/albums/album12/06.jpg",
          alt: "Photo 06",
          width: "1287",
          height: "1080",
          size: "1287x1080",
          href: "img/albums/album12/06.jpg",
        },
        {
          src: "img/albums/album12/07.jpg",
          alt: "Photo 07",
          width: "720",
          height: "1080",
          size: "720x1080",
          href: "img/albums/album12/07.jpg",
        },
        {
          src: "img/albums/album12/08.jpg",
          alt: "Photo 08",
          width: "1620",
          height: "1080",
          size: "1620x1080",
          href: "img/albums/album12/08.jpg",
        },
        {
          src: "img/albums/album12/09.jpg",
          alt: "Photo 09",
          width: "720",
          height: "1080",
          size: "720x1080",
          href: "img/albums/album12/09.jpg",
        },
        {
          src: "img/albums/album12/10.jpg",
          alt: "Photo 10",
          width: "720",
          height: "1080",
          size: "720x1080",
          href: "img/albums/album12/10.jpg",
        },
        {
          src: "img/albums/album12/11.jpg",
          alt: "Photo 11",
          width: "1620",
          height: "1080",
          size: "1620x1080",
          href: "img/albums/album12/11.jpg",
        },
        {
          src: "img/albums/album12/12.jpg",
          alt: "Photo 12",
          width: "772",
          height: "1080",
          size: "772x1080",
          href: "img/albums/album12/12.jpg",
        },
        {
          src: "img/albums/album12/13.jpg",
          alt: "Photo 13",
          width: "810",
          height: "1080",
          size: "810x1080",
          href: "img/albums/album12/13.jpg",
        },
        {
          src: "img/albums/album12/14.jpg",
          alt: "Photo 14",
          width: "1631",
          height: "1080",
          size: "1631x1080",
          href: "img/albums/album12/14.jpg",
        },
        {
          src: "img/albums/album12/15.jpg",
          alt: "Photo 15",
          width: "810",
          height: "1080",
          size: "810x1080",
          href: "img/albums/album12/15.jpg",
        },
        {
          src: "img/albums/album12/16.jpg",
          alt: "Photo 16",
          width: "810",
          height: "1080",
          size: "810x1080",
          href: "img/albums/album12/16.jpg",
        },
        {
          src: "img/albums/album12/17.jpg",
          alt: "Photo 17",
          width: "1620",
          height: "1080",
          size: "1620x1080",
          href: "img/albums/album12/17.jpg",
        },
        {
          src: "img/albums/album12/18.jpg",
          alt: "Photo 18",
          width: "608",
          height: "1080",
          size: "608x1080",
          href: "img/albums/album12/18.jpg",
        },
        {
          src: "img/albums/album12/19.jpg",
          alt: "Photo 19",
          width: "720",
          height: "1080",
          size: "720x1080",
          href: "img/albums/album12/19.jpg",
        },
        {
          src: "img/albums/album12/20.jpg",
          alt: "Photo 20",
          width: "1620",
          height: "1080",
          size: "1620x1080",
          href: "img/albums/album12/20.jpg",
        },
        {
          src: "img/albums/album12/21.jpg",
          alt: "Photo 21",
          width: "720",
          height: "1080",
          size: "720x1080",
          href: "img/albums/album12/21.jpg",
        },
        {
          src: "img/albums/album12/22.jpg",
          alt: "Photo 22",
          width: "720",
          height: "1080",
          size: "720x1080",
          href: "img/albums/album12/22.jpg",
        },
      ],
    },
    "albums-slider-parallax": {
      pageTitle: "Anita | Little Lady",
      favIconPath: "img/favicon.png",
      logoPath: "img/logo.png",
      listingType: "parallax",
      pageBackgroundSrc: "img/albums/covers_1920/album10_1920.jpg",
      albumTitle: {
        back: "Back to Listing",
        backPath: "index.html",
        title: "Little Lady",
        subtitle1: "Children",
        subtitle2: "04 Photos",
      },
      navigation: {
        subtitleLeft: "Prev Album",
        titleLeft: "Golden Feelings",
        hrefLeft: "albums-masonry-2col.html",
        srcLeft: "img/albums/covers_512/album02.jpg",
        subtitleRight: "Next Album",
        titleRight: "Sweet Harmony",
        hrefRight: "albums-masonry-3col.html",
        srcRight: "img/albums/covers_512/album04.jpg",
      },
      items: [
        {
          src: "img/albums/album03/01.jpg",
          size: "1920x1080",
        },
        {
          src: "img/albums/album03/02.jpg",
          size: "1920x1080",
        },
        {
          src: "img/albums/album03/03.jpg",
          size: "1920x1080",
        },
        {
          src: "img/albums/album03/04.jpg",
          size: "1920x1080",
        },
      ],
    },
    "albums-slider-sliced": {
      pageTitle: "Anita | Holiday Makeup",
      favIconPath: "img/favicon.png",
      logoPath: "img/logo.png",
      listingType: "sliced",
      albumTitle: {
        back: "Back to Listing",
        backPath: "index.html",
        title: "Holiday Makeup",
        subtitle1: "Portraits",
        subtitle2: "05 Photos",
      },
      navigation: {
        subtitleLeft: "Prev Album",
        titleLeft: "Sweet Harmony",
        hrefLeft: "albums-adjusted-3col.html",
        srcLeft: "img/albums/covers_512/album04.jpg",
        subtitleRight: "Next Album",
        titleRight: "The Big Day",
        hrefRight: "albums-bricks-1x2.html",
        srcRight: "img/albums/covers_512/album06.jpg",
      },
      items: [
        {
          isVideo: true,
          src: "video/albums/album05.mp4",
          size: "1280x720",
        },
        {
          src: "img/albums/album05/02.jpg",
          size: "1920x1080",
        },
        {
          src: "img/albums/album05/03.jpg",
          size: "1920x1080",
        },
        {
          src: "img/albums/album05/04.jpg",
          size: "1920x1080",
        },
        {
          src: "img/albums/album05/05.jpg",
          size: "1920x1080",
        },
      ],
    },
    "albums-slider-fade": {
      pageTitle: "Anita | Beauty of the Wild",
      favIconPath: "img/favicon.png",
      logoPath: "img/logo.png",
      listingType: "fade",
      albumTitle: {
        back: "Back to Listing",
        backPath: "index.html",
        title: "Beauty of the Wild",
        subtitle1: "Portraits",
        subtitle2: "05 Photos",
      },
      navigation: {
        subtitleLeft: "Prev Album",
        titleLeft: "Walking by Ocean",
        hrefLeft: "albums-masonry-4col.html",
        srcLeft: "img/albums/covers_512/album08.jpg",
        subtitleRight: "Next Album",
        titleRight: "Kids Happiness",
        hrefRight: "albums-adjusted-4col.html",
        srcRight: "img/albums/covers_512/album10.jpg",
      },
      items: [
        {
          isVideo: true,
          src: "video/albums/album01.mp4",
          size: "1920x1080",
        },
        {
          src: "img/albums/album09/02.jpg",
          size: "1920x1080",
        },
        {
          src: "img/albums/album09/03.jpg",
          size: "1920x1080",
        },
        {
          src: "img/albums/album09/04.jpg",
          size: "1920x1080",
        },
        {
          src: "img/albums/album09/05.jpg",
          size: "1920x1080",
        },
      ],
    },
    "albums-slider-pixels": {
      pageTitle: "Anita | Autumn Gladness",
      favIconPath: "img/favicon.png",
      logoPath: "img/logo.png",
      listingType: "pixel",
      albumTitle: {
        back: "Back to Listing",
        backPath: "index.html",
        title: "Autumn Gladness",
        subtitle1: "Children",
        subtitle2: "04 Photos",
      },
      navigation: {
        subtitleLeft: "Prev Album",
        titleLeft: "From Now and Ever",
        hrefLeft: "albums-adjusted-2col.html",
        srcLeft: "img/albums/covers_512/album13.jpg",
        subtitleRight: "Next Album",
        titleRight: "Wedding Day",
        hrefRight: "albums-grid-4col.html",
        srcRight: "img/albums/covers_512/album15.jpg",
      },
      items: [
        {
          isVideo: true,
          src: "video/albums/album01.mp4",
          size: "1920x1080",
        },
        {
          src: "img/albums/album14/02.jpg",
          size: "1920x1080",
        },
        {
          src: "img/albums/album14/03.jpg",
          size: "1920x1080",
        },
        {
          src: "img/albums/album14/04.jpg",
          size: "1920x1080",
        },
      ],
    },
    "works-carousel-flat": {
      pageTitle: "Anita | Works: Flat Carousel",
      favIconPath: "img/favicon.png",
      logoPath: "img/logo.png",
      listingType: "carousel",
      items: [
        {
          isVideo: true,
          src: "video/albums/album01.mp4",
          subtitleTop: "Portraits",
          number: "01.",
          title: "Green Turban",
          subtitleBot: "Explore",
          href: "albums-gl-carousel.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album02_1440.jpg",
          width: "1440",
          height: "1080",
          subtitleTop: "Love Story",
          number: "02.",
          title: "Golden Feelings",
          subtitleBot: "Explore",
          href: "albums-masonry-2col.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album03_1440.jpg",
          width: "1440",
          height: "1080",
          subtitleTop: "Children",
          number: "03.",
          title: "Little Lady",
          subtitleBot: "Explore",
          href: "albums-slider-parallax.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album04_1440.jpg",
          width: "1440",
          height: "1080",
          subtitleTop: "Wedding",
          number: "04.",
          title: "Sweet Harmony",
          subtitleBot: "Explore",
          href: "albums-adjusted-3col.html",
        },
        {
          isVideo: true,
          src: "video/albums/album05.mp4",
          subtitleTop: "Portraits",
          number: "05.",
          title: "Holiday Makeup",
          subtitleBot: "Explore",
          href: "albums-slider-sliced.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album06_1440.jpg",
          width: "1440",
          height: "1080",
          subtitleTop: "Wedding",
          number: "06.",
          title: "The Big Day",
          subtitleBot: "Explore",
          href: "albums-bricks-1x2.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album07_1440.jpg",
          width: "1440",
          height: "1080",
          subtitleTop: "Love Story",
          number: "07.",
          title: "When You Love",
          subtitleBot: "Explore",
          href: "albums-bricks-2x3.html",
        },
        {
          isVideo: true,
          src: "video/albums/album08.mp4",
          subtitleTop: "Children",
          number: "08.",
          title: "Walking by Ocean",
          subtitleBot: "Explore",
          href: "albums-masonry-4col.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album09_1440.jpg",
          width: "1440",
          height: "1080",
          subtitleTop: "Portraits",
          number: "09.",
          title: "Beauty of the Wild",
          subtitleBot: "Explore",
          href: "albums-slider-fade.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album10_1440.jpg",
          width: "1440",
          height: "1080",
          subtitleTop: "Children",
          number: "10.",
          title: "Kids Happiness",
          subtitleBot: "Explore",
          href: "albums-adjusted-4col.html",
        },
        {
          isVideo: true,
          src: "video/albums/album11.mp4",
          subtitleTop: "Love Story",
          number: "11.",
          title: "Día de Los Muertos",
          subtitleBot: "Explore",
          href: "albums-grid-3col.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album12_1440.jpg",
          width: "1440",
          height: "1080",
          subtitleTop: "Children",
          number: "12.",
          title: "Share Your Smile",
          subtitleBot: "Explore",
          href: "albums-justified.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album13_1440.jpg",
          width: "1440",
          height: "1080",
          subtitleTop: "Wedding",
          number: "13.",
          title: "From Now and Ever",
          subtitleBot: "Explore",
          href: "albums-adjusted-2col.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album14_1440.jpg",
          width: "1440",
          height: "1080",
          subtitleTop: "Children",
          number: "14.",
          title: "Autumn Gladness",
          subtitleBot: "Explore",
          href: "albums-slider-pixels.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album15_1440.jpg",
          width: "1440",
          height: "1080",
          subtitleTop: "Wedding",
          number: "15.",
          title: "Wedding Day",
          subtitleBot: "Explore",
          href: "albums-grid-4col.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album16_1440.jpg",
          width: "1440",
          height: "1080",
          subtitleTop: "Portraits",
          number: "16.",
          title: "Smiling Beauty",
          subtitleBot: "Explore",
          href: "albums-masonry-3col.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album17_1440.jpg",
          width: "1440",
          height: "1080",
          subtitleTop: "Love Story",
          number: "17.",
          title: "Underwater Love",
          subtitleBot: "Explore",
          href: "albums-grid-2col.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album18_1440.jpg",
          width: "1440",
          height: "1080",
          subtitleTop: "Portraits",
          number: "18.",
          title: "Bright Life Colors",
          subtitleBot: "Explore",
          href: "albums-carousel.html",
        },
      ],
    },
    "works-carousel-roll": {
      pageTitle: "Anita | Works: Roll Carousel",
      favIconPath: "img/favicon.png",
      logoPath: "img/logo.png",
      listingType: "rollCarousel",
      items: [
        {
          isVideo: true,
          src: "video/albums/album01.mp4",
          size: "1280x720",
          subtitleTop: "Portraits",
          number: "01.",
          title: "Green Turban",
          subtitleBot: "Explore",
          href: "albums-gl-carousel.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album02_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Love Story",
          number: "02.",
          title: "Golden Feelings",
          subtitleBot: "Explore",
          href: "albums-masonry-2col.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album03_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Children",
          number: "03.",
          title: "Little Lady",
          subtitleBot: "Explore",
          href: "albums-slider-parallax.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album04_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Wedding",
          number: "04.",
          title: "Sweet Harmony",
          subtitleBot: "Explore",
          href: "albums-adjusted-3col.html",
        },
        {
          isVideo: true,
          src: "video/albums/album05.mp4",
          size: "1280x720",
          subtitleTop: "Portraits",
          number: "05.",
          title: "Holiday Makeup",
          subtitleBot: "Explore",
          href: "albums-slider-sliced.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album06_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Wedding",
          number: "06.",
          title: "The Big Day",
          subtitleBot: "Explore",
          href: "albums-bricks-1x2.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album07_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Love Story",
          number: "07.",
          title: "When You Love",
          subtitleBot: "Explore",
          href: "albums-bricks-2x3.html",
        },
        {
          isVideo: true,
          src: "video/albums/album08.mp4",
          size: "1280x720",
          subtitleTop: "Children",
          number: "08.",
          title: "Walking by Ocean",
          subtitleBot: "Explore",
          href: "albums-masonry-4col.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album09_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Portraits",
          number: "09.",
          title: "Beauty of the Wild",
          subtitleBot: "Explore",
          href: "albums-slider-fade.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album10_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Children",
          number: "10.",
          title: "Kids Happiness",
          subtitleBot: "Explore",
          href: "albums-adjusted-4col.html",
        },
        {
          isVideo: true,
          src: "video/albums/album11.mp4",
          size: "1280x720",
          subtitleTop: "Love Story",
          number: "11.",
          title: "Día de Los Muertos",
          subtitleBot: "Explore",
          href: "albums-grid-3col.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album12_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Children",
          number: "12.",
          title: "Share Your Smile",
          subtitleBot: "Explore",
          href: "albums-justified.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album13_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Wedding",
          number: "13.",
          title: "From Now and Ever",
          subtitleBot: "Explore",
          href: "albums-adjusted-2col.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album14_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Children",
          number: "14.",
          title: "Autumn Gladness",
          subtitleBot: "Explore",
          href: "albums-slider-pixels.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album15_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Wedding",
          number: "15.",
          title: "Wedding Day",
          subtitleBot: "Explore",
          href: "albums-grid-4col.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album16_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Portraits",
          number: "16.",
          title: "Smiling Beauty",
          subtitleBot: "Explore",
          href: "albums-masonry-3col.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album17_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Love Story",
          number: "17.",
          title: "Underwater Love",
          subtitleBot: "Explore",
          href: "albums-grid-2col.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album18_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Portraits",
          number: "18.",
          title: "Bright Life Colors",
          subtitleBot: "Explore",
          href: "albums-carousel.html",
        },
      ],
    },
    "works-slider-fade": {
      pageTitle: "Anita | Works: Fade Slider",
      favIconPath: "img/favicon.png",
      logoPath: "img/logo.png",
      listingType: "fade",
      items: [
        {
          isVideo: true,
          src: "video/albums/album01.mp4",
          size: "1280x720",
          subtitleTop: "Portraits",
          number: "01.",
          title: "Green Turban",
          subtitleBot: "Explore",
          href: "albums-gl-carousel.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album02_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Love Story",
          number: "02.",
          title: "Golden Feelings",
          subtitleBot: "Explore",
          href: "albums-masonry-2col.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album03_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Children",
          number: "03.",
          title: "Little Lady",
          subtitleBot: "Explore",
          href: "albums-slider-parallax.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album04_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Wedding",
          number: "04.",
          title: "Sweet Harmony",
          subtitleBot: "Explore",
          href: "albums-adjusted-3col.html",
        },
        {
          isVideo: true,
          src: "video/albums/album05.mp4",
          size: "1280x720",
          subtitleTop: "Portraits",
          number: "05.",
          title: "Holiday Makeup",
          subtitleBot: "Explore",
          href: "albums-slider-sliced.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album06_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Wedding",
          number: "06.",
          title: "The Big Day",
          subtitleBot: "Explore",
          href: "albums-bricks-1x2.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album07_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Love Story",
          number: "07.",
          title: "When You Love",
          subtitleBot: "Explore",
          href: "albums-bricks-2x3.html",
        },
        {
          isVideo: true,
          src: "video/albums/album08.mp4",
          size: "1280x720",
          subtitleTop: "Children",
          number: "08.",
          title: "Walking by Ocean",
          subtitleBot: "Explore",
          href: "albums-masonry-4col.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album09_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Portraits",
          number: "09.",
          title: "Beauty of the Wild",
          subtitleBot: "Explore",
          href: "albums-slider-fade.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album10_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Children",
          number: "10.",
          title: "Kids Happiness",
          subtitleBot: "Explore",
          href: "albums-adjusted-4col.html",
        },
        {
          isVideo: true,
          src: "video/albums/album11.mp4",
          size: "1280x720",
          subtitleTop: "Love Story",
          number: "11.",
          title: "Día de Los Muertos",
          subtitleBot: "Explore",
          href: "albums-grid-3col.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album12_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Children",
          number: "12.",
          title: "Share Your Smile",
          subtitleBot: "Explore",
          href: "albums-justified.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album13_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Wedding",
          number: "13.",
          title: "From Now and Ever",
          subtitleBot: "Explore",
          href: "albums-adjusted-2col.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album14_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Children",
          number: "14.",
          title: "Autumn Gladness",
          subtitleBot: "Explore",
          href: "albums-slider-pixels.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album15_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Wedding",
          number: "15.",
          title: "Wedding Day",
          subtitleBot: "Explore",
          href: "albums-grid-4col.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album16_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Portraits",
          number: "16.",
          title: "Smiling Beauty",
          subtitleBot: "Explore",
          href: "albums-masonry-3col.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album17_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Love Story",
          number: "17.",
          title: "Underwater Love",
          subtitleBot: "Explore",
          href: "albums-grid-2col.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album18_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Portraits",
          number: "18.",
          title: "Bright Life Colors",
          subtitleBot: "Explore",
          href: "albums-carousel.html",
        },
      ],
    },
    "works-slider-parallax": {
      pageTitle: "Anita | Works: Parallax Slider",
      favIconPath: "img/favicon.png",
      logoPath: "img/logo.png",
      listingType: "pixel",
      items: [
        {
          isVideo: true,
          src: "video/albums/album01.mp4",
          size: "1280x720",
          subtitleTop: "Portraits",
          number: "01.",
          title: "Green Turban",
          subtitleBot: "Explore",
          href: "albums-gl-carousel.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album02_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Love Story",
          number: "02.",
          title: "Golden Feelings",
          subtitleBot: "Explore",
          href: "albums-masonry-2col.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album03_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Children",
          number: "03.",
          title: "Little Lady",
          subtitleBot: "Explore",
          href: "albums-slider-parallax.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album04_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Wedding",
          number: "04.",
          title: "Sweet Harmony",
          subtitleBot: "Explore",
          href: "albums-adjusted-3col.html",
        },
        {
          isVideo: true,
          src: "video/albums/album05.mp4",
          size: "1280x720",
          subtitleTop: "Portraits",
          number: "05.",
          title: "Holiday Makeup",
          subtitleBot: "Explore",
          href: "albums-slider-sliced.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album06_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Wedding",
          number: "06.",
          title: "The Big Day",
          subtitleBot: "Explore",
          href: "albums-bricks-1x2.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album07_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Love Story",
          number: "07.",
          title: "When You Love",
          subtitleBot: "Explore",
          href: "albums-bricks-2x3.html",
        },
        {
          isVideo: true,
          src: "video/albums/album08.mp4",
          size: "1280x720",
          subtitleTop: "Children",
          number: "08.",
          title: "Walking by Ocean",
          subtitleBot: "Explore",
          href: "albums-masonry-4col.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album09_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Portraits",
          number: "09.",
          title: "Beauty of the Wild",
          subtitleBot: "Explore",
          href: "albums-slider-fade.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album10_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Children",
          number: "10.",
          title: "Kids Happiness",
          subtitleBot: "Explore",
          href: "albums-adjusted-4col.html",
        },
        {
          isVideo: true,
          src: "video/albums/album11.mp4",
          size: "1280x720",
          subtitleTop: "Love Story",
          number: "11.",
          title: "Día de Los Muertos",
          subtitleBot: "Explore",
          href: "albums-grid-3col.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album12_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Children",
          number: "12.",
          title: "Share Your Smile",
          subtitleBot: "Explore",
          href: "albums-justified.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album13_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Wedding",
          number: "13.",
          title: "From Now and Ever",
          subtitleBot: "Explore",
          href: "albums-adjusted-2col.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album14_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Children",
          number: "14.",
          title: "Autumn Gladness",
          subtitleBot: "Explore",
          href: "albums-slider-pixels.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album15_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Wedding",
          number: "15.",
          title: "Wedding Day",
          subtitleBot: "Explore",
          href: "albums-grid-4col.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album16_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Portraits",
          number: "16.",
          title: "Smiling Beauty",
          subtitleBot: "Explore",
          href: "albums-masonry-3col.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album17_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Love Story",
          number: "17.",
          title: "Underwater Love",
          subtitleBot: "Explore",
          href: "albums-grid-2col.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album18_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Portraits",
          number: "18.",
          title: "Bright Life Colors",
          subtitleBot: "Explore",
          href: "albums-carousel.html",
        },
      ],
    },
    "works-slider-pixels": {
      pageTitle: "Anita | Works: Pixel Storm Slider",
      favIconPath: "img/favicon.png",
      logoPath: "img/logo.png",
      listingType: "parallax",
      items: [
        {
          isVideo: true,
          src: "video/albums/album01.mp4",
          size: "1280x720",
          subtitleTop: "Portraits",
          number: "01.",
          title: "Green Turban",
          subtitleBot: "Explore",
          href: "albums-gl-carousel.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album02_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Love Story",
          number: "02.",
          title: "Golden Feelings",
          subtitleBot: "Explore",
          href: "albums-masonry-2col.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album03_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Children",
          number: "03.",
          title: "Little Lady",
          subtitleBot: "Explore",
          href: "albums-slider-parallax.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album04_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Wedding",
          number: "04.",
          title: "Sweet Harmony",
          subtitleBot: "Explore",
          href: "albums-adjusted-3col.html",
        },
        {
          isVideo: true,
          src: "video/albums/album05.mp4",
          size: "1280x720",
          subtitleTop: "Portraits",
          number: "05.",
          title: "Holiday Makeup",
          subtitleBot: "Explore",
          href: "albums-slider-sliced.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album06_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Wedding",
          number: "06.",
          title: "The Big Day",
          subtitleBot: "Explore",
          href: "albums-bricks-1x2.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album07_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Love Story",
          number: "07.",
          title: "When You Love",
          subtitleBot: "Explore",
          href: "albums-bricks-2x3.html",
        },
        {
          isVideo: true,
          src: "video/albums/album08.mp4",
          size: "1280x720",
          subtitleTop: "Children",
          number: "08.",
          title: "Walking by Ocean",
          subtitleBot: "Explore",
          href: "albums-masonry-4col.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album09_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Portraits",
          number: "09.",
          title: "Beauty of the Wild",
          subtitleBot: "Explore",
          href: "albums-slider-fade.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album10_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Children",
          number: "10.",
          title: "Kids Happiness",
          subtitleBot: "Explore",
          href: "albums-adjusted-4col.html",
        },
        {
          isVideo: true,
          src: "video/albums/album11.mp4",
          size: "1280x720",
          subtitleTop: "Love Story",
          number: "11.",
          title: "Día de Los Muertos",
          subtitleBot: "Explore",
          href: "albums-grid-3col.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album12_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Children",
          number: "12.",
          title: "Share Your Smile",
          subtitleBot: "Explore",
          href: "albums-justified.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album13_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Wedding",
          number: "13.",
          title: "From Now and Ever",
          subtitleBot: "Explore",
          href: "albums-adjusted-2col.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album14_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Children",
          number: "14.",
          title: "Autumn Gladness",
          subtitleBot: "Explore",
          href: "albums-slider-pixels.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album15_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Wedding",
          number: "15.",
          title: "Wedding Day",
          subtitleBot: "Explore",
          href: "albums-grid-4col.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album16_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Portraits",
          number: "16.",
          title: "Smiling Beauty",
          subtitleBot: "Explore",
          href: "albums-masonry-3col.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album17_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Love Story",
          number: "17.",
          title: "Underwater Love",
          subtitleBot: "Explore",
          href: "albums-grid-2col.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album18_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Portraits",
          number: "18.",
          title: "Bright Life Colors",
          subtitleBot: "Explore",
          href: "albums-carousel.html",
        },
      ],
    },
    "works-slider-sliced": {
      pageTitle: "Anita | Works: Sliced Slider",
      favIconPath: "img/favicon.png",
      logoPath: "img/logo.png",
      listingType: "sliced",
      items: [
        {
          isVideo: true,
          src: "video/albums/album01.mp4",
          size: "1280x720",
          subtitleTop: "Portraits",
          number: "01.",
          title: "Green Turban",
          subtitleBot: "Explore",
          href: "albums-gl-carousel.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album02_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Love Story",
          number: "02.",
          title: "Golden Feelings",
          subtitleBot: "Explore",
          href: "albums-masonry-2col.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album03_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Children",
          number: "03.",
          title: "Little Lady",
          subtitleBot: "Explore",
          href: "albums-slider-parallax.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album04_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Wedding",
          number: "04.",
          title: "Sweet Harmony",
          subtitleBot: "Explore",
          href: "albums-adjusted-3col.html",
        },
        {
          isVideo: true,
          src: "video/albums/album05.mp4",
          size: "1280x720",
          subtitleTop: "Portraits",
          number: "05.",
          title: "Holiday Makeup",
          subtitleBot: "Explore",
          href: "albums-slider-sliced.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album06_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Wedding",
          number: "06.",
          title: "The Big Day",
          subtitleBot: "Explore",
          href: "albums-bricks-1x2.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album07_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Love Story",
          number: "07.",
          title: "When You Love",
          subtitleBot: "Explore",
          href: "albums-bricks-2x3.html",
        },
        {
          isVideo: true,
          src: "video/albums/album08.mp4",
          size: "1280x720",
          subtitleTop: "Children",
          number: "08.",
          title: "Walking by Ocean",
          subtitleBot: "Explore",
          href: "albums-masonry-4col.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album09_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Portraits",
          number: "09.",
          title: "Beauty of the Wild",
          subtitleBot: "Explore",
          href: "albums-slider-fade.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album10_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Children",
          number: "10.",
          title: "Kids Happiness",
          subtitleBot: "Explore",
          href: "albums-adjusted-4col.html",
        },
        {
          isVideo: true,
          src: "video/albums/album11.mp4",
          size: "1280x720",
          subtitleTop: "Love Story",
          number: "11.",
          title: "Día de Los Muertos",
          subtitleBot: "Explore",
          href: "albums-grid-3col.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album12_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Children",
          number: "12.",
          title: "Share Your Smile",
          subtitleBot: "Explore",
          href: "albums-justified.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album13_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Wedding",
          number: "13.",
          title: "From Now and Ever",
          subtitleBot: "Explore",
          href: "albums-adjusted-2col.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album14_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Children",
          number: "14.",
          title: "Autumn Gladness",
          subtitleBot: "Explore",
          href: "albums-slider-pixels.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album15_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Wedding",
          number: "15.",
          title: "Wedding Day",
          subtitleBot: "Explore",
          href: "albums-grid-4col.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album16_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Portraits",
          number: "16.",
          title: "Smiling Beauty",
          subtitleBot: "Explore",
          href: "albums-masonry-3col.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album17_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Love Story",
          number: "17.",
          title: "Underwater Love",
          subtitleBot: "Explore",
          href: "albums-grid-2col.html",
        },
        {
          isVideo: false,
          src: "img/albums/covers_1440/album18_1440.jpg",
          size: "1440x1080",
          subtitleTop: "Portraits",
          number: "18.",
          title: "Bright Life Colors",
          subtitleBot: "Explore",
          href: "albums-carousel.html",
        },
      ],
    },
  },
};
